DTRUNETWO-297-Added get&listTransferStatusTransition
hyperwallet/java-sdk pull request #105
Opened 2020-11-10 17:06 UTC by jkurra-hw

2020-11-10 19:00 UTC, Rrathinasabapath approved these changes
Verified the changes to be fine. Can be merged after a review by Aparna and Vadim/Peter.

2020-11-11 18:12 UTC, arao6 approved these changes

2020-11-11 18:37 UTC, arao6 requested changes
Please add a test case for ListTransferStatusTransition with null options.
Also could you please rename your branch to feature-v3/DTRUNETWO-297-V3JAVASDK-Transfers

2020-11-12 07:25 UTC, jkurra-hw commented
> Please add a test case for ListTransferStatusTransition with null options.
> Also could you please rename your branch to feature-v3/DTRUNETWO-297-V3JAVASDK-Transfers

@arao6  renamed branch name to feature-v3/DTRUNETWO-297-V3JAVASDK-Transfers and added test case with null options .

2020-11-13 04:54 UTC, arao6 approved these changes

2020-11-13 21:52 UTC, wmews-hw approved these changes

2020-11-13 22:28 UTC, merged