Feature v3/dtrunetwo 298 v3 javasdk transfer refunds
hyperwallet/java-sdk pull request #114
Opened 2020-11-17 09:51 UTC by jkurra-hw

2020-11-18 19:39 UTC, arao6 approved these changes

2020-11-19 08:07 UTC, Rrathinasabapath requested changes
Pls add the requested comment for a method and push the code.

2020-11-19 18:18 UTC, Rrathinasabapath commented on src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java
> +    private HyperwalletTransferRefund copy(HyperwalletTransferRefund transferRefund) {
Approving as the comments for other similar methods will be added in the next release.

2020-11-19 18:19 UTC, Rrathinasabapath approved these changes
Approved

2020-11-19 18:20 UTC, vkorotchenko approved these changes

2020-11-20 05:47 UTC, merged