V3 java ppplmer 95761 update query parameters b
hyperwallet/java-sdk pull request #135
Opened 2021-06-26 19:52 UTC by Rrathinasabapath

Please review the changes and approve for the list methods of the following resources:

- Venmo Accounts
- Prepaid Cards
- Paper Checks
- Transfer Methods
- Payments

2021-07-14 12:23 UTC, ramahalingam commented on src/main/java/com/hyperwallet/clientsdk/model/HyperwalletVenmoAccountListPaginationOptions.java
> +    private Date createdOn;
Do we need to specify format here?

2021-07-14 12:24 UTC, ramahalingam requested changes
Pls check the comments.

2021-07-15 14:24 UTC, ramahalingam approved these changes

2021-07-27 18:15 UTC, vkorotchenko approved these changes

2021-07-27 18:58 UTC, arao6 approved these changes

2021-07-27 18:58 UTC, merged