Changes for HW-66706 V4PrepaidCards
hyperwallet/java-sdk pull request #76
Opened 2020-09-07 13:11 UTC by ramahalingam

2020-09-08 14:35 UTC, Rrathinasabapath approved these changes
Reviewed the changes

2020-09-08 15:52 UTC, Rrathinasabapath requested changes
Please check if returnValue.getLinks() check has to be done. Could the return value be null or not-null depending on an uncontrolled factor? This is the same comment as that of #79

2020-09-09 10:36 UTC, Rrathinasabapath approved these changes
Reviewed the code. Its ready for a review by Vadim.

2020-09-10 16:59 UTC, vkorotchenko approved these changes

2020-09-11 17:41 UTC, merged